# Generated by Django 4.0.6 on 2022-07-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_director_movies_director'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
